[package]
name = "resource-issuer-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.resource-issuer]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.4"
default-features = false
